// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvLRvOVbdmW7wrjEVRPNO4xMydCvsRug',
    appId: '1:66821906023:web:10adf9bbcadcb498ed7ec2',
    messagingSenderId: '66821906023',
    projectId: 'anime-83266',
    authDomain: 'anime-83266.firebaseapp.com',
    storageBucket: 'anime-83266.firebasestorage.app',
    measurementId: 'G-SJMR2RH8MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQ038DZSFq3UkOTkU4tMg8sPwcvBIR14',
    appId: '1:66821906023:android:567eff1e3ba81150ed7ec2',
    messagingSenderId: '66821906023',
    projectId: 'anime-83266',
    storageBucket: 'anime-83266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ouzVhPAxTO9h1SJZ4gEjGVjjza28Psk',
    appId: '1:66821906023:ios:8efe03e61fb2b6d2ed7ec2',
    messagingSenderId: '66821906023',
    projectId: 'anime-83266',
    storageBucket: 'anime-83266.firebasestorage.app',
    iosBundleId: 'com.example.animaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ouzVhPAxTO9h1SJZ4gEjGVjjza28Psk',
    appId: '1:66821906023:ios:8efe03e61fb2b6d2ed7ec2',
    messagingSenderId: '66821906023',
    projectId: 'anime-83266',
    storageBucket: 'anime-83266.firebasestorage.app',
    iosBundleId: 'com.example.animaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgvLRvOVbdmW7wrjEVRPNO4xMydCvsRug',
    appId: '1:66821906023:web:ce181f1b1181e131ed7ec2',
    messagingSenderId: '66821906023',
    projectId: 'anime-83266',
    authDomain: 'anime-83266.firebaseapp.com',
    storageBucket: 'anime-83266.firebasestorage.app',
    measurementId: 'G-C7QNYPWQPE',
  );
}
